name: Docker Image CI

on:
    pull_request:
      types: [opened, reopened]

env:
    GITHUB_ORG_NAME: ${{ vars.GH_ORG_NAME }}
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
#
jobs:
    unittest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies & run app
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              python github-reporting-tool.py